[HyperParam]
epochs = 400
lr = 8e-3
batch_size = 512
weight_decay = 1e-4
dropout = 0.1
beta_1 = 0.9
beta_2 = 0.999
warmup_steps = 100

num_layers = 3
d_model = 512 
num_heads = 8
mlp_hiddens = 2048
img_size = 32
patch_size = 4
num_classes = 10
